<?php

/**
 * BaseCommit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $project_id
 * @property string $author
 * @property timestamp $timestamp
 * @property string $message
 * @property Project $Project
 * @property Doctrine_Collection $FileChange
 * 
 * @method string              getId()         Returns the current record's "id" value
 * @method integer             getProjectId()  Returns the current record's "project_id" value
 * @method string              getAuthor()     Returns the current record's "author" value
 * @method timestamp           getTimestamp()  Returns the current record's "timestamp" value
 * @method string              getMessage()    Returns the current record's "message" value
 * @method Project             getProject()    Returns the current record's "Project" value
 * @method Doctrine_Collection getFileChange() Returns the current record's "FileChange" collection
 * @method Commit              setId()         Sets the current record's "id" value
 * @method Commit              setProjectId()  Sets the current record's "project_id" value
 * @method Commit              setAuthor()     Sets the current record's "author" value
 * @method Commit              setTimestamp()  Sets the current record's "timestamp" value
 * @method Commit              setMessage()    Sets the current record's "message" value
 * @method Commit              setProject()    Sets the current record's "Project" value
 * @method Commit              setFileChange() Sets the current record's "FileChange" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseCommit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commit');
        $this->hasColumn('id', 'string', 200, array(
             'type' => 'string',
             'primary' => true,
             'length' => '200',
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('timestamp', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasMany('FileChange', array(
             'local' => 'id',
             'foreign' => 'commit_id'));
    }
}