<?php

/**
 * BaseFileChange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $commit_id
 * @property string $file_path
 * @property string $change_type
 * @property Commit $Commit
 * 
 * @method string     getCommitId()    Returns the current record's "commit_id" value
 * @method string     getFilePath()    Returns the current record's "file_path" value
 * @method string     getChangeType()  Returns the current record's "change_type" value
 * @method Commit     getCommit()      Returns the current record's "Commit" value
 * @method FileChange setCommitId()    Sets the current record's "commit_id" value
 * @method FileChange setFilePath()    Sets the current record's "file_path" value
 * @method FileChange setChangeType()  Sets the current record's "change_type" value
 * @method FileChange setCommit()      Sets the current record's "Commit" value
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseFileChange extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_change');
        $this->hasColumn('commit_id', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('file_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('change_type', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commit', array(
             'local' => 'commit_id',
             'foreign' => 'id'));
    }
}