<?php

/**
 * BaseFileChangeType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $icon
 * @property Doctrine_Collection $FileChange
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getIcon()       Returns the current record's "icon" value
 * @method Doctrine_Collection getFileChange() Returns the current record's "FileChange" collection
 * @method FileChangeType      setName()       Sets the current record's "name" value
 * @method FileChangeType      setIcon()       Sets the current record's "icon" value
 * @method FileChangeType      setFileChange() Sets the current record's "FileChange" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseFileChangeType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_change_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('icon', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FileChange', array(
             'local' => 'id',
             'foreign' => 'file_change_type_id'));
    }
}