<?php

/**
 * BaseScmType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $default_port
 * @property Doctrine_Collection $Scm
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getDefaultPort()  Returns the current record's "default_port" value
 * @method Doctrine_Collection getScm()          Returns the current record's "Scm" collection
 * @method ScmType             setName()         Sets the current record's "name" value
 * @method ScmType             setDefaultPort()  Sets the current record's "default_port" value
 * @method ScmType             setScm()          Sets the current record's "Scm" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseScmType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scm_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('default_port', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Scm', array(
             'local' => 'id',
             'foreign' => 'scm_type_id'));
    }
}