<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $scm_id
 * @property Scm $Scm
 * @property Doctrine_Collection $Commit
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method integer             getScmId()  Returns the current record's "scm_id" value
 * @method Scm                 getScm()    Returns the current record's "Scm" value
 * @method Doctrine_Collection getCommit() Returns the current record's "Commit" collection
 * @method Project             setName()   Sets the current record's "name" value
 * @method Project             setScmId()  Sets the current record's "scm_id" value
 * @method Project             setScm()    Sets the current record's "Scm" value
 * @method Project             setCommit() Sets the current record's "Commit" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('scm_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Scm', array(
             'local' => 'scm_id',
             'foreign' => 'id'));

        $this->hasMany('Commit', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}