<?php

/**
 * BaseCommit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $revision
 * @property integer $scm_id
 * @property string $author
 * @property timestamp $timestamp
 * @property string $message
 * @property Scm $Scm
 * @property Doctrine_Collection $FileChange
 * 
 * @method string              getRevision()   Returns the current record's "revision" value
 * @method integer             getScmId()      Returns the current record's "scm_id" value
 * @method string              getAuthor()     Returns the current record's "author" value
 * @method timestamp           getTimestamp()  Returns the current record's "timestamp" value
 * @method string              getMessage()    Returns the current record's "message" value
 * @method Scm                 getScm()        Returns the current record's "Scm" value
 * @method Doctrine_Collection getFileChange() Returns the current record's "FileChange" collection
 * @method Commit              setRevision()   Sets the current record's "revision" value
 * @method Commit              setScmId()      Sets the current record's "scm_id" value
 * @method Commit              setAuthor()     Sets the current record's "author" value
 * @method Commit              setTimestamp()  Sets the current record's "timestamp" value
 * @method Commit              setMessage()    Sets the current record's "message" value
 * @method Commit              setScm()        Sets the current record's "Scm" value
 * @method Commit              setFileChange() Sets the current record's "FileChange" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseCommit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commit');
        $this->hasColumn('revision', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('scm_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('author', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('timestamp', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));


        $this->index('revision', array(
             'fields' => 
             array(
              'revision' => 
              array(
              ),
              'scm_id' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Scm', array(
             'local' => 'scm_id',
             'foreign' => 'id'));

        $this->hasMany('FileChange', array(
             'local' => 'revision',
             'foreign' => 'commit_revision'));
    }
}