<?php

/**
 * BaseScm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $scm_type_id
 * @property string $host
 * @property integer $port
 * @property string $username
 * @property string $password
 * @property string $path
 * @property ScmType $ScmType
 * @property Doctrine_Collection $Commit
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getScmTypeId()   Returns the current record's "scm_type_id" value
 * @method string              getHost()        Returns the current record's "host" value
 * @method integer             getPort()        Returns the current record's "port" value
 * @method string              getUsername()    Returns the current record's "username" value
 * @method string              getPassword()    Returns the current record's "password" value
 * @method string              getPath()        Returns the current record's "path" value
 * @method ScmType             getScmType()     Returns the current record's "ScmType" value
 * @method Doctrine_Collection getCommit()      Returns the current record's "Commit" collection
 * @method Scm                 setName()        Sets the current record's "name" value
 * @method Scm                 setScmTypeId()   Sets the current record's "scm_type_id" value
 * @method Scm                 setHost()        Sets the current record's "host" value
 * @method Scm                 setPort()        Sets the current record's "port" value
 * @method Scm                 setUsername()    Sets the current record's "username" value
 * @method Scm                 setPassword()    Sets the current record's "password" value
 * @method Scm                 setPath()        Sets the current record's "path" value
 * @method Scm                 setScmType()     Sets the current record's "ScmType" value
 * @method Scm                 setCommit()      Sets the current record's "Commit" collection
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseScm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scm');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('scm_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('host', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('port', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScmType', array(
             'local' => 'scm_type_id',
             'foreign' => 'id'));

        $this->hasMany('Commit', array(
             'local' => 'id',
             'foreign' => 'scm_id'));
    }
}