<?php

/**
 * FileChange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    phpCodeControl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class FileChange extends BaseFileChange
{
  public function findPrevious()
  {
    // if this is an addition, return null
    if ($this->getFileChangeTypeId() == 1)
    {
      return null;
    }
    
    // get the previous commit which contains a file with the same file_path
    return Doctrine_Query::create()->
            addFrom('Commit c')->
            innerJoin('c.FileChange fc')->
            where('c.scm_id=?', $this->getCommit()->getScmId())->
            andWhere('fc.file_path=?', $this->getFilePath())->
            andWhere('c.timestamp < ?', $this->getCommit()->getTimestamp())->
            addOrderBy('c.timestamp DESC')->
            limit(1)->
            fetchOne();
  }
}
