# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        phpCodeControl
    description:  SCM Tracking tool
    #keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    [../sfJqueryReloadedPlugin/css/black-tie/jquery-ui-1.8.1.custom.css, main.css]

  javascripts:    [../sfJqueryReloadedPlugin/js/jquery-1.4.2.min.js, ../sfJqueryReloadedPlugin/js/plugins/jquery-ui-1.8.1.custom.min.js]

  has_layout:     true
  layout:         layout
