ScmType:
  columns:
    name:         { type: string(50), notnull: true }
    default_port: { type: integer, notnull: true }

Scm:
  columns:
    name:        { type: string(100), notnull: true }
    scm_type_id: { type: integer, notnull: true }
    host:        { type: string, notnull: true }
    port:        { type: integer }
    username:    { type: string(255) }
    password:    { type: string(255) }
    path:        { type: string, notnull: true }
  relations:
    ScmType:     ~

Commit:
  columns:
    revision:   { type: string(200), notnull: true }
    scm_id:     { type: integer, notnull: true }
    author:     { type: string(100), notnull: true }
    timestamp:  { type: timestamp, notnull: true }
    message:    { type: string, notnull: true }
  relations:
    Scm:        ~
  indexes:
    revision:
      fields:
        revision: []
        scm_id: []
      type: unique

FileChangeType:
  columns:
    name: { type: string(50), notnull: true }
    icon: { type: string(50), notnull: true }

FileChange:
  columns:
    commit_revision:     { type: string(200), notnull: true }
    file_path:           { type: string, notnull: true }
    file_change_type_id: { type: integer, notnull: true }
    insertions:          { type: integer, notnull: false } # only filled after indexing
    deletions:           { type: integer, notnull: false } # only filled after indexing
  relations:
    Commit:              { local: commit_revision, foreign: revision }
    FileChangeType:      ~