ScmType:
  columns:
    name:         { type: string(50), notnull: true }
    default_port: { type: integer, notnull: true }

Scm:
  columns:
    scm_type_id: { type: integer, notnull: true }
    host:        { type: string, notnull: true }
    port:        { type: integer }
    username:    { type: string(255), notnull: true }
    password:    { type: string(255), notnull: true }
    path:        { type: string, notnull: true }
  relations:
    ScmType:     ~

Commit:
  columns:
    id:         { type: string(200), primary: true }
    scm_id:     { type: integer, notnull: true }
    author:     { type: string(100), notnull: true }
    timestamp:  { type: timestamp, notnull: true }
    message:    { type: string, notnull: true }
  relations:
    Scm:        ~

FileChangeType:
  columns:
    name: { type: string(50), notnull: true }
    icon: { type: string(50), notnull: true }

FileChange:
  columns:
    commit_id:           { type: string(200), notnull: true }
    file_path:           { type: string, notnull: true }
    file_change_type_id: { type: integer, notnull: true }
  relations:
    Commit:              ~
    FileChangeType:      ~